import { AppConfig, Mustahiq, MuzakkiTransaction, DistributionRecord, SkKemenagTier } from '../types/zakat';

export const DEFAULT_SK_TIERS: SkKemenagTier[] = [
  {
    id: 'tier-1',
    name: 'Kategori I (Beras Super / Premium)',
    riceType: 'Pandan Wangi, Rojolele, Mentik Wangi, dll.',
    pricePerSoulRp: 55000,
    description: 'Beras kualitas super/premium konsumsi harian',
  },
  {
    id: 'tier-2',
    name: 'Kategori II (Beras Menengah Atas / Ramos)',
    riceType: 'Setra Ramos, C4, Ramos Bandung, dll.',
    pricePerSoulRp: 45000,
    description: 'Beras kualitas sedang ke atas (paling umum digunakan warga)',
  },
  {
    id: 'tier-3',
    name: 'Kategori III (Beras Standar / Medium)',
    riceType: 'IR-64, Beras Bulog Premium, dll.',
    pricePerSoulRp: 40000,
    description: 'Beras kualitas standar konsumsi masyarakat umum',
  },
  {
    id: 'tier-4',
    name: 'Kategori IV (Beras Sederhana / SPHP)',
    riceType: 'Beras SPHP / Medium Bulog',
    pricePerSoulRp: 35000,
    description: 'Beras kualitas dasar sesuai ketetapan terendah edaran SK',
  },
];

export const DEFAULT_CONFIG: AppConfig = {
  organizationName: 'UPZ Panitia Zakat Masjid Baiturrahim',
  subTitle: 'Unit Pengumpul Zakat (UPZ) DKM Baiturrahim',
  hijriYear: '1447 H',
  masehiYear: '2026 M',
  address: 'Jl. Melati No. 18, Kelurahan Sukamaju',
  phone: '0812-3456-7890',
  headAmil: 'H. Ahmad Syarifuddin',
  treasurerName: 'Ust. Muhammad Ridwan',
  fitrahRiceKgPerSoul: 2.8,
  fitrahRiceOptions: [2.5, 2.7, 2.8, 3.0, 3.5],
  skKemenagReference: 'SK Bersama Kemenag & BAZNAS No. 1447 H / 2026 M',
  skKemenagTiers: DEFAULT_SK_TIERS,
  fitrahMoneyPerSoul: 45000,
  goldPricePerGram: 1450000,
  silverPricePerGram: 18000,
  grainHarvestNisabKg: 653,
  ricePricePerKgForNisab: 15000,
  goatPricePerHead: 2500000,
  cowPricePerHead: 14000000,
  fidyahRatePerDay: 30000,
};

export const INITIAL_TRANSACTIONS: MuzakkiTransaction[] = [
  {
    id: 'tx-1001',
    receiptNumber: 'ZKT-1447-0001',
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
    dateStr: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    name: 'Bpk. Hendra Gunawan',
    phone: '0813-8877-6655',
    address: 'Jl. Merpati No. 4',
    rtRw: 'Jamaah Masjid',
    category: 'fitrah',
    fitrahDetail: {
      payerCount: 4,
      familyMembers: ['Hendra Gunawan', 'Siti Nurhaliza (Istri)', 'Faris Hendra (Anak)', 'Aisyah Hendra (Anak)'],
      unit: 'uang',
      riceWeightKg: 0,
      nominalRp: 180000,
      ratePerPerson: 45000,
      skKemenagTierId: 'tier-2',
      skKemenagTierName: 'Kategori II (Beras Menengah Atas / Ramos)',
    },
    paymentMethod: 'tunai',
    amilName: 'Ust. Muhammad Ridwan',
    notes: 'Zakat fitrah sekeluarga 4 jiwa (uang kategori II SK Kemenag)',
    totalMoneyRp: 180000,
    totalRiceKg: 0,
  },
  {
    id: 'tx-1002',
    receiptNumber: 'ZKT-1447-0002',
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
    dateStr: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    name: 'Ibu Rahmawati',
    phone: '0857-1122-3344',
    address: 'Jl. Anggrek No. 12',
    rtRw: 'Jamaah Masjid',
    category: 'fitrah',
    fitrahDetail: {
      payerCount: 3,
      familyMembers: ['Rahmawati', 'Dimas Prasetyo (Anak)', 'Nabila (Anak)'],
      unit: 'beras',
      riceWeightKg: 8.4,
      nominalRp: 0,
      ratePerPerson: 2.8,
      riceWeightPerSoulKg: 2.8,
    },
    paymentMethod: 'tunai',
    amilName: 'H. Ahmad Syarifuddin',
    notes: 'Beras pandan wangi 3 kantong @ 2.8 kg (ihtiyath)',
    totalMoneyRp: 0,
    totalRiceKg: 8.4,
  },
  {
    id: 'tx-1003',
    receiptNumber: 'ZKT-1447-0003',
    timestamp: new Date(Date.now() - 86400000 * 1).toISOString(),
    dateStr: new Date(Date.now() - 86400000 * 1).toISOString().split('T')[0],
    name: 'Bpk. Ir. H. Bambang Susilo',
    phone: '0811-9988-7766',
    address: 'Komplek Permata Indah Blok B-9',
    rtRw: 'Jamaah Masjid',
    category: 'maal',
    maalDetail: {
      assetType: 'tabungan_emas',
      totalAssetRp: 150000000,
      nominalRp: 3750000,
      nisabMet: true,
    },
    paymentMethod: 'transfer_qris',
    amilName: 'Ust. Muhammad Ridwan',
    notes: 'Zakat Maal tabungan 1 tahun haul (2.5%)',
    totalMoneyRp: 3750000,
    totalRiceKg: 0,
  },
  {
    id: 'tx-1004',
    receiptNumber: 'ZKT-1447-0004',
    timestamp: new Date().toISOString(),
    dateStr: new Date().toISOString().split('T')[0],
    name: 'dr. Anisa Wardani',
    phone: '0812-7766-5544',
    address: 'Jl. Flamboyan No. 21',
    rtRw: 'Luar Lingkungan / Jamaah Tamu',
    category: 'profesi',
    profesiDetail: {
      monthlyIncomeRp: 20000000,
      nominalRp: 500000,
    },
    paymentMethod: 'transfer_qris',
    amilName: 'Ust. Muhammad Ridwan',
    notes: 'Zakat profesi dokter bulanan',
    totalMoneyRp: 500000,
    totalRiceKg: 0,
  },
  {
    id: 'tx-1005',
    receiptNumber: 'ZKT-1447-0005',
    timestamp: new Date().toISOString(),
    dateStr: new Date().toISOString().split('T')[0],
    name: 'Ibu Hj. Mariyam',
    phone: '0878-5544-3322',
    address: 'Jl. Kenanga No. 7',
    rtRw: 'Jamaah Masjid',
    category: 'fidyah',
    fidyahDetail: {
      daysCount: 15,
      ratePerDayRp: 30000,
      nominalRp: 450000,
    },
    paymentMethod: 'tunai',
    amilName: 'H. Ahmad Syarifuddin',
    notes: 'Fidyah puasa Ramadhan 15 hari sakit sepuh',
    totalMoneyRp: 450000,
    totalRiceKg: 0,
  },
  {
    id: 'tx-1006',
    receiptNumber: 'ZKT-1447-0006',
    timestamp: new Date().toISOString(),
    dateStr: new Date().toISOString().split('T')[0],
    name: 'Hamba Allah',
    phone: '-',
    address: 'Lingkungan Masjid',
    rtRw: 'Luar Lingkungan / Jamaah Tamu',
    category: 'infaq',
    infaqDetail: {
      nominalRp: 250000,
      allocation: 'operasional_masjid',
    },
    paymentMethod: 'tunai',
    amilName: 'Ust. Muhammad Ridwan',
    notes: 'Sedekah operasional amil & dkm',
    totalMoneyRp: 250000,
    totalRiceKg: 0,
  },
];

export const INITIAL_MUSTAHIQ: Mustahiq[] = [
  {
    id: 'mst-101',
    name: 'Bpk. Kakek Sutarman',
    nik: '3201123456780001',
    kkNumber: '3201123456780000',
    phone: '0896-1234-5678',
    address: 'Gang Kelinci No. 05 RT 02 / RW 07',
    rtRw: 'RT 02 / RW 07',
    asnaf: 'fakir',
    familyMembersCount: 2,
    priority: 'sangat_mendesak',
    status: 'aktif',
    notes: 'Lansia sebatang kara dengan cucu yatim, tidak memiliki penghasilan tetap',
    totalRiceReceivedKg: 5,
    totalMoneyReceivedRp: 150000,
    lastDistributedAt: new Date(Date.now() - 86400000).toISOString().split('T')[0],
  },
  {
    id: 'mst-102',
    name: 'Ibu Aminah (Janda)',
    nik: '3201123456780002',
    phone: '0819-8765-4321',
    address: 'Jl. Melati RT 01 / RW 07',
    rtRw: 'RT 01 / RW 07',
    asnaf: 'miskin',
    familyMembersCount: 4,
    priority: 'sangat_mendesak',
    status: 'aktif',
    notes: 'Buruh cuci keliling menghidupi 3 orang anak sekolah',
    totalRiceReceivedKg: 7.5,
    totalMoneyReceivedRp: 200000,
    lastDistributedAt: new Date(Date.now() - 86400000).toISOString().split('T')[0],
  },
  {
    id: 'mst-103',
    name: 'Sdr. Daniel Saputra (Mualaf)',
    nik: '3201123456780003',
    phone: '0852-3344-5566',
    address: 'Kos Pondok Sejahtera RT 03 / RW 07',
    rtRw: 'RT 03 / RW 07',
    asnaf: 'mualaf',
    familyMembersCount: 1,
    priority: 'mendesak',
    status: 'aktif',
    notes: 'Baru bersyahadat 4 bulan lalu, membutuhkan penguatan dan dukungan ekonomi',
    totalRiceReceivedKg: 5,
    totalMoneyReceivedRp: 250000,
    lastDistributedAt: new Date().toISOString().split('T')[0],
  },
  {
    id: 'mst-104',
    name: 'Ust. Hasan Basri (Guru Ngaji TPA)',
    nik: '3201123456780004',
    phone: '0812-4455-6677',
    address: 'Rumah Dinas Kaum Belakang Masjid',
    rtRw: 'RT 03 / RW 07',
    asnaf: 'fisabilillah',
    familyMembersCount: 5,
    priority: 'reguler',
    status: 'aktif',
    notes: 'Pengajar Al-Quran anak-anak kampung sukarela tanpa honor tetap',
    totalRiceReceivedKg: 0,
    totalMoneyReceivedRp: 0,
  },
  {
    id: 'mst-105',
    name: 'Bpk. Slamet Riyadi',
    nik: '3201123456780005',
    phone: '0858-9988-1122',
    address: 'Gang Buntu No. 11 RT 04 / RW 07',
    rtRw: 'RT 04 / RW 07',
    asnaf: 'miskin',
    familyMembersCount: 3,
    priority: 'mendesak',
    status: 'aktif',
    notes: 'Pedagang asongan, gerobak rusak pasca banjir',
    totalRiceReceivedKg: 0,
    totalMoneyReceivedRp: 0,
  },
  {
    id: 'mst-106',
    name: 'Bpk. Badrun (Korban Hutang Berobat)',
    nik: '3201123456780006',
    phone: '0821-3344-9988',
    address: 'Jl. Kamboja No. 16 RT 02 / RW 07',
    rtRw: 'RT 02 / RW 07',
    asnaf: 'gharimin',
    familyMembersCount: 3,
    priority: 'mendesak',
    status: 'aktif',
    notes: 'Terlilit hutang biaya operasi istri, tidak memiliki aset berharga',
    totalRiceReceivedKg: 0,
    totalMoneyReceivedRp: 0,
  }
];

export const INITIAL_DISTRIBUTIONS: DistributionRecord[] = [
  {
    id: 'dist-001',
    dateStr: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    mustahiqId: 'mst-101',
    mustahiqName: 'Bpk. Kakek Sutarman',
    asnaf: 'fakir',
    rtRw: 'RT 02 / RW 07',
    riceKg: 5,
    moneyRp: 150000,
    packageDescription: 'Paket Beras 5 Kg + Santunan Tunai',
    distributorAmil: 'Ust. Muhammad Ridwan',
    notes: 'Diserahkan langsung ke kediaman mustahiq',
  },
  {
    id: 'dist-002',
    dateStr: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    mustahiqId: 'mst-102',
    mustahiqName: 'Ibu Aminah (Janda)',
    asnaf: 'miskin',
    rtRw: 'RT 01 / RW 07',
    riceKg: 7.5,
    moneyRp: 200000,
    packageDescription: 'Paket Beras 7.5 Kg + Uang Sembako',
    distributorAmil: 'H. Ahmad Syarifuddin',
    notes: 'Diambil di posko amil masjid',
  },
  {
    id: 'dist-003',
    dateStr: new Date().toISOString().split('T')[0],
    timestamp: new Date().toISOString(),
    mustahiqId: 'mst-103',
    mustahiqName: 'Sdr. Daniel Saputra (Mualaf)',
    asnaf: 'mualaf',
    rtRw: 'RT 03 / RW 07',
    riceKg: 5,
    moneyRp: 250000,
    packageDescription: 'Paket Beras 5 Kg + Santunan Mualaf',
    distributorAmil: 'Ust. Muhammad Ridwan',
    notes: 'Penyaluran asnaf mualaf',
  }
];
